[workspace]
authors = ["John Jackson <jdjacks@post.harvard.edu>"]
channels = ["conda-forge"]
name = "napari-cool-tools-plugins"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
# We need a python version that is compatible with pytorch
python = ">=3.9,<3.12"

[pypi-dependencies]
numpy = "==1.23.5"
PyQt5-Qt5 = "==5.15.2"
PyQt5 = "==5.15.*"
napari = "==0.5.2"
napari-cool-tools-img-proc = { path = "napari-cool-tools-img-proc", editable = true }
napari-cool-tools-io = { path = "napari-cool-tools-io", editable = true }
napari-cool-tools-oct-preproc = { path = "napari-cool-tools-oct-preproc", editable = true }
napari-cool-tools-registration = { path = "napari-cool-tools-registration", editable = true }
napari-cool-tools-segmentation = { path = "napari-cool-tools-segmentation", editable = true }
napari-cool-tools-vol-proc = { path = "napari-cool-tools-vol-proc", editable = true }
napari-cool-tools-submenu-patch = { path = "napari-cool-tools-submenu-patch", editable = true }
kornia = "==0.8.*"
flatbuffers = "==25.2.*"
packaging = "==24.*"
protobuf = "==6.30.*"
matplotlib = "==3.9.*"
ruamel-yaml = "==0.18.6"
tomlkit = "==0.13.*"
opencv-python = "==4.11.0.*"

[feature.development]
[feature.development.pypi-dependencies]
segmentation-models-pytorch = "==0.4.0"
tensorboard = "==2.19.0"
notebook = "==7.4.3"
onnx = "==1.16.2"
qtreload = "==0.2.3"
polars = "==1.31.*"
imreg_dft = "==2.0.0"
#pypcd4 = "==1.2.1"
#pyvista = "==0.45.*"

[feature.visualization]
[feature.visualization.pypi-dependencies]
#open3d = "==0.19.0"
pypcd4 = "==1.2.1"
#pptk = "==0.1.0"
pyvista = "==0.45.*"
pyvistaqt = "==0.11.*"
openpyxl = "*"

[feature.cuda11]
system-requirements = { cuda = "11.0" }
[feature.cuda11.pypi-dependencies]
nvidia-cuda-runtime-cu11 = "==11.8.*"
torch = { version = "==2.4.*", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "==0.19.*", index = "https://download.pytorch.org/whl/cu118" }
torchaudio = { version = "==2.4.*", index = "https://download.pytorch.org/whl/cu118" }
onnxruntime-gpu = { version = "==1.19.*", index = "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple/" }
optuna = "==4.3.*"
cupy-cuda11x = "==13.4.*"
tensorrt = "==10.2.*"
tensorrt-cu11-libs = "==10.2.*"
tensorrt-cu11-bindings = "==10.2.*"

[feature.cuda12]
system-requirements = { cuda = "12.0" }
[feature.cuda12.pypi-dependencies]
nvidia-cuda-runtime-cu12 = "==12.4.*"
torch = { version = "==2.4.*", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "==0.19.*", index = "https://download.pytorch.org/whl/cu124" }
torchaudio = { version = "==2.4.*", index = "https://download.pytorch.org/whl/cu124" }
onnxruntime-gpu = { version = "==1.19.*", index = "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/" }
optuna = "==4.3.*"
cupy-cuda12x = "==13.4.*"
tensorrt = "==10.2.*"
tensorrt-cu12-libs = "==10.2.*"
tensorrt-cu12-bindings = "==10.2.*"


[feature.cpu.pypi-dependencies]
torch = { version = "==2.4.*", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = "==0.19.*", index = "https://download.pytorch.org/whl/cpu" }
torchaudio = { version = "==2.4.*", index = "https://download.pytorch.org/whl/cpu" }
onnxruntime = "==1.19.*, <2"

[environments]
dev = { features = ["development"]}
cpu = { features = ["cpu"]}
cuda11 = { features = ["cuda11"] }
cuda12 = { features = ["cuda12"] }
cpu-dev = { features =  ["development","cpu"] }
cuda11-dev = { features = ["development", "cuda11"] }
#cuda12-dev = { features = ["development", "cuda12"] }
cuda12-dev = { features = ["development", "cuda12", "visualization"] }

## Make CPU the default environment
#default = { features = ["cpu"] }


[environments.default]
features = ["cuda12", "development", "visualization"]
